import type { CourseId, ReadingText } from './types'

/**
 * Readlang/LingQ-style reading content + RussianPod101/Ruspeach-style graded dialogues.
 * All texts use frequency-first vocab already in the course; words outside it get an
 * inline `glossary`. Original/own content only — never copied from those sites.
 *
 * Audio for these texts is pre-generated by `scripts/gen-audio.py` (phrase + per-word),
 * so taps and the per-line 🔊 button use neural MP3s instead of Web Speech fallback.
 */
export const readings: Record<CourseId, ReadingText[]> = {
  ru: [
    {
      id: 'ru-read-morning',
      title: 'Моё утро',
      level: 'A1',
      kind: 'story',
      body: 'Привет! Я хочу чай. У меня есть хлеб и сыр. Это очень хорошо!\n\nКот хочет молоко. Собака хочет воду. Спасибо!',
      translation:
        'Hi! I want tea. I have bread and cheese. This is very good! The cat wants milk. The dog wants water. Thank you!',
      glossary: { 'моё': 'my', 'утро': 'morning', 'и': 'and', 'хочет': 'wants' },
    },
    {
      id: 'ru-dlg-cafe',
      title: 'В кафе',
      level: 'A1',
      kind: 'dialogue',
      turns: [
        { speaker: 'Анна', text: 'Здравствуйте!', translation: 'Hello!' },
        { speaker: 'Официант', text: 'Здравствуйте! Что вы хотите?', translation: 'Hello! What do you want?' },
        { speaker: 'Анна', text: 'Я хочу кофе и хлеб, пожалуйста.', translation: 'I want coffee and bread, please.' },
        { speaker: 'Официант', text: 'Хорошо.', translation: 'Good.' },
        { speaker: 'Анна', text: 'Спасибо! До свидания.', translation: 'Thank you! Goodbye.' },
      ],
      glossary: { 'официант': 'waiter', 'хотите': '(you) want', 'и': 'and' },
      questions: [
        {
          q: 'What does Anna want?',
          options: ['Coffee and bread', 'Tea and cheese', 'Water', 'Soup'],
          correctIndex: 0,
        },
        {
          q: 'How does Anna say goodbye?',
          options: ['До свидания', 'Привет', 'Спасибо', 'Да'],
          correctIndex: 0,
        },
      ],
    },
    {
      id: 'ru-read-family',
      title: 'Моя семья',
      level: 'A1',
      kind: 'story',
      body: 'Это моя семья. Мама и папа дома. Брат читает книгу.\n\nСестра работает в городе. У меня есть кот и собака. Я очень люблю свою семью!',
      translation:
        'This is my family. Mom and dad are at home. Brother is reading a book. Sister works in the city. I have a cat and a dog. I really love my family!',
      glossary: { 'моя': 'my', 'семья': 'family', 'дома': 'at home', 'и': 'and', 'свою': 'my own' },
    },
    {
      id: 'ru-dlg-shop',
      title: 'В магазине',
      level: 'A1',
      kind: 'dialogue',
      turns: [
        { speaker: 'Продавец', text: 'Здравствуйте! Что вам нужно?', translation: 'Hello! What do you need?' },
        { speaker: 'Клиент', text: 'Мне нужен хлеб и сыр, пожалуйста.', translation: 'I need bread and cheese, please.' },
        { speaker: 'Продавец', text: 'Хорошо. Что ещё?', translation: 'Good. What else?' },
        { speaker: 'Клиент', text: 'Яблоко и воду, пожалуйста. Сколько это стоит?', translation: 'An apple and water, please. How much is it?' },
        { speaker: 'Продавец', text: 'Пять рублей. Спасибо!', translation: 'Five rubles. Thank you!' },
        { speaker: 'Клиент', text: 'До свидания!', translation: 'Goodbye!' },
      ],
      glossary: { 'продавец': 'shop assistant', 'клиент': 'customer', 'вам': 'to you', 'нужен': 'needed (m.)', 'ещё': 'else', 'рублей': 'rubles' },
      questions: [
        {
          q: 'What does the customer want?',
          options: ['Bread and cheese', 'Coffee', 'Water', 'Soup'],
          correctIndex: 0,
        },
        {
          q: 'How much does it cost?',
          options: ['Five rubles', 'Ten rubles', 'Nothing', 'Two rubles'],
          correctIndex: 0,
        },
      ],
    },
    {
      id: 'ru-read-weather',
      title: 'Погода',
      level: 'A2',
      kind: 'story',
      body: 'Сегодня хорошая погода. Солнце светит. Мама и папа гуляют в парке.\n\nЯ читаю книгу дома. Кот спит. Вечером мы пьём чай.',
      translation:
        'Today the weather is nice. The sun is shining. Mom and dad are walking in the park. I am reading a book at home. The cat is sleeping. In the evening we drink tea.',
      glossary: {
        'погода': 'weather',
        'хорошая': 'good (f.)',
        'светит': 'shines',
        'гуляют': 'walk (they)',
        'парке': 'in the park',
        'спит': 'sleeps',
        'вечером': 'in the evening',
        'пьём': 'we drink',
      },
    },
    {
      id: 'ru-dlg-park',
      title: 'В парке',
      level: 'A2',
      kind: 'dialogue',
      turns: [
        { speaker: 'Анна', text: 'Привет! Как дела?', translation: 'Hi! How are you?' },
        { speaker: 'Борис', text: 'Привет! У меня всё хорошо. А у тебя?', translation: 'Hi! I am fine. And you?' },
        { speaker: 'Анна', text: 'Тоже хорошо. Хочешь гулять в парке?', translation: 'Also fine. Do you want to walk in the park?' },
        { speaker: 'Борис', text: 'Да! Давай.', translation: 'Yes! Let\'s go.' },
        { speaker: 'Анна', text: 'До свидания!', translation: 'Goodbye!' },
      ],
      glossary: { 'дела': 'things', 'всё': 'everything', 'тебя': 'you (acc.)', 'тоже': 'also', 'гулять': 'to walk', 'давай': 'let\'s', 'а': 'and' },
      questions: [
        {
          q: 'How does Anna say goodbye?',
          options: ['До свидания', 'Привет', 'Спасибо', 'Да'],
          correctIndex: 0,
        },
        {
          q: 'Does Boris want to go?',
          options: ['Yes', 'No', 'Later', 'He is tired'],
          correctIndex: 0,
        },
      ],
    },
  ],
  es: [
    {
      id: 'es-read-morning',
      title: 'Mi mañana',
      level: 'A1',
      kind: 'story',
      body: '¡Hola! Quiero café. Tengo pan y queso. ¡Esto es muy bien!\n\nEl gato quiere leche. El perro quiere agua. ¡Gracias!',
      translation:
        'Hi! I want coffee. I have bread and cheese. This is very good! The cat wants milk. The dog wants water. Thank you!',
      glossary: { 'mi': 'my', 'mañana': 'morning', 'y': 'and', 'quiere': 'wants' },
    },
    {
      id: 'es-dlg-cafe',
      title: 'En el café',
      level: 'A1',
      kind: 'dialogue',
      turns: [
        { speaker: 'Ana', text: '¡Hola!', translation: 'Hi!' },
        { speaker: 'Camarero', text: '¡Hola! ¿Qué quiere?', translation: 'Hi! What do you want?' },
        { speaker: 'Ana', text: 'Quiero café y pan, por favor.', translation: 'I want coffee and bread, please.' },
        { speaker: 'Camarero', text: 'Bien.', translation: 'Good.' },
        { speaker: 'Ana', text: '¡Gracias! Adiós.', translation: 'Thank you! Goodbye.' },
      ],
      glossary: { 'camarero': 'waiter', 'quiere': 'do you want', 'y': 'and' },
      questions: [
        {
          q: 'What does Ana want?',
          options: ['Coffee and bread', 'Tea and cheese', 'Water', 'Soup'],
          correctIndex: 0,
        },
        {
          q: 'How does Ana say goodbye?',
          options: ['Adiós', 'Hola', 'Gracias', 'Sí'],
          correctIndex: 0,
        },
      ],
    },
    {
      id: 'es-read-family',
      title: 'Mi familia',
      level: 'A1',
      kind: 'story',
      body: 'Esta es mi familia. Mamá y papá están en casa. Mi hermano lee un libro.\n\nMi hermana trabaja en la ciudad. Tenemos un gato y un perro. ¡Yo amo a mi familia!',
      translation:
        'This is my family. Mom and dad are at home. My brother reads a book. My sister works in the city. We have a cat and a dog. I love my family!',
      glossary: { 'esta': 'this (f.)', 'mi': 'my', 'familia': 'family', 'están': 'are', 'lee': 'reads', 'tenemos': 'we have', 'y': 'and', 'a': 'to' },
    },
    {
      id: 'es-dlg-shop',
      title: 'En la tienda',
      level: 'A1',
      kind: 'dialogue',
      turns: [
        { speaker: 'Vendedor', text: '¡Hola! ¿Qué necesita?', translation: 'Hi! What do you need?' },
        { speaker: 'Cliente', text: 'Necesito pan y queso, por favor.', translation: 'I need bread and cheese, please.' },
        { speaker: 'Vendedor', text: 'Muy bien. ¿Algo más?', translation: 'Very good. Anything else?' },
        { speaker: 'Cliente', text: 'Una manzana y agua, por favor. ¿Cuánto cuesta?', translation: 'An apple and water, please. How much is it?' },
        { speaker: 'Vendedor', text: 'Son dos euros. ¡Gracias!', translation: 'That is two euros. Thank you!' },
        { speaker: 'Cliente', text: '¡Adiós!', translation: 'Goodbye!' },
      ],
      glossary: { 'vendedor': 'shop assistant', 'cliente': 'customer', 'necesita': 'need (you)', 'necesito': 'I need', 'algo': 'something', 'más': 'more', 'cuesta': 'costs', 'euros': 'euros', 'son': 'they are', 'y': 'and' },
      questions: [
        {
          q: 'What does the customer want?',
          options: ['Bread and cheese', 'Water', 'An apple', 'Meat'],
          correctIndex: 0,
        },
        {
          q: 'How much does it cost?',
          options: ['Two euros', 'Five rubles', 'Free', 'One dollar'],
          correctIndex: 0,
        },
      ],
    },
    {
      id: 'es-read-weather',
      title: 'El tiempo',
      level: 'A2',
      kind: 'story',
      body: 'Hoy hace buen tiempo. El sol brilla. Mamá y papá pasean en el parque.\n\nYo leo un libro en casa. El gato duerme. Por la tarde bebemos té.',
      translation:
        'Today the weather is nice. The sun is shining. Mom and dad stroll in the park. I read a book at home. The cat is sleeping. In the afternoon we drink tea.',
      glossary: {
        'tiempo': 'weather',
        'hace': 'it is',
        'brilla': 'shines',
        'sol': 'sun',
        'pasean': 'stroll (they)',
        'parque': 'park',
        'leo': 'I read',
        'duerme': 'sleeps',
        'tarde': 'afternoon',
        'bebemos': 'we drink',
        'y': 'and',
      },
    },
    {
      id: 'es-dlg-park',
      title: 'En el parque',
      level: 'A2',
      kind: 'dialogue',
      turns: [
        { speaker: 'Ana', text: '¡Hola! ¿Cómo estás?', translation: 'Hi! How are you?' },
        { speaker: 'Luis', text: '¡Hola! Estoy bien, gracias. ¿Y tú?', translation: 'Hi! I am fine, thanks. And you?' },
        { speaker: 'Ana', text: 'También bien. ¿Quieres pasear en el parque?', translation: 'Also fine. Do you want to walk in the park?' },
        { speaker: 'Luis', text: '¡Sí! Vamos.', translation: 'Yes! Let\'s go.' },
        { speaker: 'Ana', text: '¡Adiós!', translation: 'Goodbye!' },
      ],
      glossary: { 'estás': 'are (you)', 'estoy': 'I am', 'tú': 'you', 'también': 'also', 'quieres': 'want (you)', 'pasear': 'to walk', 'vamos': 'let\'s go', 'y': 'and' },
      questions: [
        {
          q: 'How does Ana say goodbye?',
          options: ['Adiós', 'Hola', 'Gracias', 'Sí'],
          correctIndex: 0,
        },
        {
          q: 'Does Luis want to go?',
          options: ['Yes', 'No', 'Later', 'He is tired'],
          correctIndex: 0,
        },
      ],
    },
  ],
}
